# Generated by Django 4.0.2 on 2022-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=15)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=254)),
            ],
        ),
    ]
