# Generated by Django 4.0.2 on 2022-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_base_type_alter_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='base_type',
            field=models.CharField(choices=[('UAH', 'Hryvnia'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'Bitcoin')], default='UAH', max_length=10),
        ),
    ]
