# Generated by Django 4.0.2 on 2022-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('reply_to', models.EmailField(max_length=15)),
                ('subject', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=1024)),
                ('raw_content', models.TextField()),
            ],
        ),
    ]
