# Generated by Django 4.0.2 on 2022-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_rate_base_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'OschadBank'), (5, 'Ukrsibbank'), (6, 'Raiffeisen')], unique=True),
        ),
    ]
